uclaradio/uclaradio.com

public/css/WaterFallContent.css
react/frontpage/WaterFallContent.jsx

Links that are formatted improperly will cause the entire description to not post on the homepage

links not formatted properly will be ignored

---

public/css/WaterFallContent.css
react/frontpage/WaterFallContent.jsx
react/frontpage/responsive_waterfall.js

frontend component of tumblr-posts

Transpose waterfall chronology and display tumblr blog posts as well

---

package.json
public/css/WaterFallContent.css
react/frontpage/WaterFallContent.jsx
react/frontpage/responsive_waterfall.js
routes/index.js

This pull request is for BACKEND only - waterfall react component will be modified at a later time

Tumblr posts

---

public/css/WaterFallContent.css
react/frontpage/WaterFallContent.jsx
routes/index.js

As you scroll downwards, more tiles populate the front page.  Currently only retrieves more facebook data, will factor in tumblr later (but also still deciding bc tumblr throws a lot of data at you and is p slow).

Infinite Waterfall Scroll (Facebook posts)

---

LICENSE.md
README.md

Added a [MIT](https://opensource.org/licenses/MIT) license notice and update the readme to reflect that. In response to #87.
We're officially open source now lol

Add a license

---

public/frontpage.html

Somehow this was removed? No worries though, because show icons are back.

Add Font Awesome CDN

---

README.md
package.json
setup.sh

There's this cool package called [concurrently](https://github.com/kimmobrunfeldt/concurrently) that lets you run multiple commands in package.json. Since we have to `npm start` and `grunt build`, I figured it'd be easier to just consolidate both commands. Check it out: you only have to run `npm start`!

Simplify Development Process

---

.gitignore
database/rivendell.js
package.json
public/panel/css/elrond.css
public/panel/css/panel.css
public/panel/elrond.html
react/panelElrond.jsx
routes/panel.js

Reverts uclaradio/uclaradio#104
I messed up twice -- please ignore :")

Revert "Revert "Elrond - Rivendell Library Viewer""

---

react/frontpage/components/WaterFallContent.jsx

the dates display as they should in both chrome and safari

Resolved NaN bug in Safari

---

database/shows.js

When a new show is created Make Public is checked by default.

Update to make shows public by default

---

views/pages.jade

Updated the archive link for 2017–2018. This is already deployed lol.

Update Archive Link

---

.github/issue_template.md
.github/pull_request_template.md

There were a couple minor annoyances in the Pull Request and issue templates, namely that comments appeared if they were in the same line as a header and that two checkboxes in the PR template could be combined.
I moved the comments onto new lines and combined the checkboxes into one checkbox!
Not much really. I just found these things annoying and changed them.

Make a couple minor .github changes

---

.travis.yml
README.md

We need a continuous integration platform. [Travis CI](https://travis-ci.org) seems like the best one out there for our needs.
Adds a `.travis.yml` file so that we can integrate our repo with Travis. I haven't added any tests, but we'll handle that with later pull requests.
A __lot__ of thinking and research went into this. Travis seems like the best CI solution because it is the most popular and free for open source projects!
__Operating System:__ N/A
__Node Version:__ N/A

Add Travis CI Integration

---

README.md
database/scripts/setupPanel.js
package.json
setup.sh
yarn.lock

Often times packages are added or removed in new branches. This commit adds a [post-checkout hook](https://git-scm.com/docs/githooks#_post_checkout) via [husky](https://github.com/typicode/husky) that runs yarn so that all needed packages are installed.
I just added a postcommit section in our scripts section of `package.json`! I also update the readme and install script so that they support yarn.
I was reading about git hooks, learned about post-commit and was inspired because I forget to install my packages all the time.
```shell
in ~/D/U/uclaradio on nathan/git-checkout-hook
› rm -rf node_modules/
in ~/D/U/uclaradio on nathan/git-checkout-hook
› git checkout .
husky > npm run -s postcheckout (node v8.3.0)
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] …
```

Add post-checkout hook to run yarn

---

client/react/frontpage/components/ShowPage.js

Corrects error we were getting when directly linking to a show page (as opposed to navigating to it through the schedule)
See: https://github.com/uclaradio/uclaradio/issues/117
Check for missing show property in render method of showPage component before attempting to access properties of the object or do anything else
Saw that the error mentioned that the djs property of some non-object variable could not be accessed, visited the showPage component and looked for any `.djs` strings in the page, indicating the object was being accessed and noticed we were doing so as `show.djs` before checking if the show property of the component actually existed, smh

Fix direct link to show page error

---

client/react/frontpage/components/ChatBox.js

MORE button on the chat box did not load messages.
messages.peek() within getNext() wasn't a function. Replaced with messages[0].
None

Fixed chatbox MORE button to load previous messages.

---

client/react/frontpage/components/ChatBox.scss

- [x ] Bugfix (change which fixes an issue)
Chatbox was grayed out on Firefox. Fixed the CSS.
Webkit causes issues on Firefox. Replaced webkit CSS functions (webkit-mask-image to mask-image and webkit-gradient to linear-gradient).
Looked on Mozilla CSS reference.

Fixed Firefox chatbox CSS error

---

client/react/frontpage/components/AboutPage.js

Email Typo in About Page #173
Did a find all in the client folder and changed the one result from `radio.info@media.ucla.com` to `radio.info@media.ucla.edu`
N/A
I was not able to successfully start the dev environment on my windows 10 desktop, I received the following errors when trying to run `yarn dev`:
```
projects\contributing-projects\uclaradio> yarn dev
yarn run v1.2.1
warning You are using Node "9.0.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || ^8.0.0"
$ concurrently  --kill-others 'yarn run watch' 'yarn run assets' --names '💻,📦' --prefix name
['💻] 'yar' is not recognized as an internal or external command,
['💻] operable program or batch file.
[📦'] 'run' is not recognized as an …
```

Fixed radio.info@media.ucla.edu email on about page 

---

app/database/db.js

We've been getting this error:
```
(node:26962) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
```
Whenever starting up the site. This fixes that!
I went to [the link in the error message](http://mongoosejs.com/docs/connections.html#use-mongo-client) and it seemed like the only fix we had to make was to add `{ useMongoClient: true }` to our `.connect` call. 
No error!

Fix Mongo deprecation error

---

client/react/frontpage/Frontpage.js
client/react/frontpage/components/SocialPanel.js
client/react/frontpage/components/SocialPanel.scss

Adds a social media link panel to the home page.
Resolves #83 
Wrote a React component that generates Font Awesome icons as links to various social media pages, and added it to the FrontpageContent component. 
Uses an array of objects that stores the base icon name and URL for each link, in an effort to be more maintainable.
__Operating System:__ macOS Sierra
__Node Version:__ 6.11.5
Tested on my dev environment!

Add social panel

---

client/react/frontpage/components/FrontPageNavbar.js

We changed the blog URL, so let's update the site to reflect that!

Update blog link to blog.uclaradio.com

---

client/views/pages.jade

issue #192: removed photo video request form

---

client/react/frontpage/components/EventList.scss

Fix the selected show dot such that it displays the same shade of red as the selected show box instead of grey
Removed a line of css that overrode the styling as formatted in shows
How to use developer tools in Firefox and find where a particular style is within the files

Fix selected show dot

---

client/react/frontpage/Frontpage.js
client/react/frontpage/components/DJList/DJInfo.js
client/react/frontpage/components/DJList/DJList.js
client/react/frontpage/components/DJList/DJList.scss

Reorganized two components (DJList & DJInfo along with stylesheets) by moving them into a new subfolder called DJInfo. 
New folder in Components titled DJInfo that contains:
DJList.js
DJList.scss
DJInfo.js

Move DJList and DJInfo components into subfolder

---

client/react/frontpage/components/StreamBar.js
client/react/frontpage/components/StreamBar.scss
package.json
yarn.lock

https://github.com/uclaradio/uclaradio.com/issues/191
Added popover to stream bar
Leveraged React Slider: https://github.com/react-component/slider

Add volume control

---

client/react/frontpage/Frontpage.js

Update Spotlight Week 2 Spring 2018

---

client/react/frontpage/Frontpage.js

Pledge is officially over! Part 1 of transitioning the site back to regular uclaradio.com

Remove modal after pledge drive

---

client/views/pages.jade
package-lock.json
package.json
yarn.lock

Needed to update information for new quarter.
Three lines changed in pages.jade.
Replace Spring 18 with Fall 18 title in Roster card object
Replace the outdated string literal link for roster google form and for google drive archive respectively

Update Roster and Archive links in Pages for Fall '18

---

app/database/scripts/testSocket.js
app/routes/chat.js

Checks that a message sent across the socket has both a user and text field in the JSON, otherwise `new message` doesn't get emitted. 
Script included (s/o to Arjun) for testing the socket on localhost. 

Check for malformed message

---

app/routes/api.js
client/public/frontpage.html
client/react/frontpage/components/StreamBar/StreamBar.js

Adds compatibility for listening to stream on UCLA_WEB/UCLA_WEB_RES.
Avoids requiring NGINX to rewrite the old stream addresses to the new
https one.
Allow stream to work on firewalled networks, like UCLA_WEB/UCLA_WEB_RES.
Use a reverse proxy on the server side to forward stream (port 8000) to an https address.
NGINX on server side for proxying.
__Operating System:__  Debian Buster   
__Node Version:__ v10.10.0

Use https for stream instead of port 8000.

---

app/routes/index.js
client/react/frontpage/components/BlogPage.js
client/react/frontpage/components/BlogPostPage.js

Continuation of this PR! [257](https://github.com/uclaradio/uclaradio.com/pull/257)
I renamed "article" to "post" to be consistent with the renaming in the keystone api

renamed article to post

---

README.md
app/database/blogposts.js
app/database/scripts/addTumblrPosts.js
app/routes/index.js
client/react/frontpage/components/BlogPage.js
package.json

We originally didn't want to store tumblr posts in the database. We originally were fetching from the tumblr API (which you can do 50 posts at a time). This became an issue when we were trying to filter or search all our blog posts (which include tumblr posts). You need some sort of cache or database to keep track of all the posts to look through. We had been trying to do a janky way on the frontend, but doing this on the backend is way easier and makes it a lot more clearer for what the frontend is supposed to do. 
I created a script `app/database/scripts/addTumblrPosts.js`  that uses the Tumblr client to query the API for several iterations until we've queried all the existing tumblr posts. This script can also be run from yarn and has been added to the `package.json` accordingly. 
I …

Tumblr posts are now fetched and seeded into DB. 

---

app/database/blogposts.js
client/react/frontpage/components/BlogPage.js
client/react/frontpage/components/BlogPage.scss
client/react/frontpage/components/FilterBar.js
client/react/frontpage/components/FilterBar.scss
passwords.json~
yarn.lock

lmao me making a pr for katie 
Filtering looked ugly and now it doesn't.

Blog Filter Bar and Pagination Styling

---

.github/pull_request_template.md

Testing is very useful bc otherwise idk how to use ur code. Also, I want people to start using the Issues tab because it's a better way of being organized.
Updated the `pull_request_template.md`

Added testing and issue link to pr template

---

client/react/frontpage/components/BlogPage.js

Previously, posts' content fields were being displayed with character entity references and HTML tags explicitly visible. This was fixed by changing the code to access Tumblr posts' author fields' `textContent` instead of `innerHTML`.
A little bit of Googling. StackOverflow always pulls through!
| **Before** | **After** |
| --- | --- |
| ![screenshot_20190304_171421](https://user-images.githubusercontent.com/30734384/53774370-0a01eb00-3ea3-11e9-969a-81db14b3f711.png) | ![screenshot_20190304_172911](https://user-images.githubusercontent.com/30734384/53774374-0f5f3580-3ea3-11e9-8e16-8e6b3e0745cb.png) |
#312

Fixed bug for displaying blog posts

---

app/routes/index.js
client/react/frontpage/components/BlogPage.js

Before, there was a bug with displaying blog posts, where they didn't appear to be sorted correctly---some posts from 2016 were interleaved with posts from 2019 (see **Screenshots** below), for example. A small change to the `sort` call's [`compareFunction`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Syntax) fixed this.
Some trial and error regarding placing `console.log` statements revealed the source of the problem; with a little bit of StackOverflow-ing, a solution was found.
Idk how react works lol
| **Before** | **After** |
| --- | --- |
| ![screenshot_20190304_165803](https://user-images.githubusercontent.com/30734384/53773408-374c9a00-3e9f-11e9-9ab9-1261d36eafab.png) | ![screenshot_20190304_165816](https://user-images.githubuserconten …

Fix blogpost sorting

---

client/react/frontpage/components/BlogPage.js
client/react/frontpage/components/BlogPage.scss
client/react/frontpage/components/FilterBar.js
client/react/frontpage/components/Pagination.js
client/react/frontpage/components/Pagination.scss

Can now navigate blog page by changing page number on input
https://github.com/uclaradio/uclaradio.com/issues/296

Input pagination bug fix

---

client/react/frontpage/components/BlogPage.js
client/react/frontpage/components/BlogPostPage.js

Previously, the Keystone UI involved users having to add <imgNumber> to be parsed from the uclaradio.com frontend. It's now parsed as <ImageNumber>, probably because this is more intuitive. I just replaced that string in the relevant places. I also added a welcome header that allows users to checkout the old tumblr.
Replaced a bunch of strings.

Image Parsing with New Labels

---

app/database/blogposts.js
app/database/scripts/addTumblrPosts.js
app/routes/index.js
client/react/frontpage/components/BlogPage.js
client/react/frontpage/components/BlogPostPage.js
client/react/frontpage/components/FilterBar.js
client/react/frontpage/components/FrontPageNavbar.js

We currently store both Tumblr posts from the old blog and Keystone posts from the new Admin UI. Previously, we implemented filtering the tumblr posts by parsing the `tags` object from Tumblr. This involved Ishaan and I manually adding a corresponding tag to each of the tumblr posts. Since we want old tumblr posts to be incorporated with the new blog's filtering feature, we didn't want to manually add tags to the existing tumblr posts (734 posts). Instead, Mia used machine learning to sort the existing tumblr posts into categories. 
Mia's script categorized all the existing tumblr posts into the relevant categories: "Show Reviews", "Music Reviews". She used the title and content to sort. To create the training set, she used the titles. Once she does that, she uses the training sets …

Filtering with Mia's ML Script

---

client/react/frontpage/components/Pagination.js

Before, blogpost pagination was indexed at 0. That is not intuitive for anyone but those with some experience with CS, so this PR changes indexing to start at 1.
| **Before** | **After** |
| --- | --- |
| ![screenshot_20190305_172348](https://user-images.githubusercontent.com/30734384/53849140-bb6c5380-3f6b-11e9-8cf0-da982c74de8f.png) | ![screenshot_20190305_172417](https://user-images.githubusercontent.com/30734384/53849149-bf987100-3f6b-11e9-9ee1-dd4972df04ec.png) |
#321

Changed pagination index to be 1-indexed

---

client/react/frontpage/components/BlogPage.js
client/react/frontpage/components/Pagination.js

When a filter is applied or a search is performed, the page number needs to return to 0.
Ugh, so much Googling and trial and error (and a little bit of the [docs](https://reactjs.org/docs/react-component.html#componentdidupdate)).
#319 and #323

Reset page on filter or search

---

client/react/frontpage/Frontpage.js
client/react/frontpage/components/BlogFilterBar.js
client/react/frontpage/components/BlogPage.js

Now that we've migrated our blog, turns out loading 700+ posts takes a while, so we need to display the loading icon while we're waiting for it.
#334

Add loading icon

---

client/react/frontpage/components/BlogPage.js
client/react/frontpage/components/BlogPage.scss

When performing a search, if there are no matching results then the entire blog post page changes to a single "No posts!" string, requiring a refresh.
#341

Fix "No posts!" being displayed when there are no search results

---

client/react/frontpage/components/BlogPostPage.js

Image parsing doesn't fully work. One of the new posts' code looks like this:
```html
...
&lt;</span></em><span style=\"font-size: 12pt; font-family: 'Times New Roman'; color: #000000; background-color: transparent; font-weight: 400; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;\">Image1&gt;
...
```
The old parser replaced occurrences of `&lt;Image1&gt;`, so it failed on this image because of the extra tags between `&lt;` and `Image1&gt;`.
The fix is to use regular expressions, such that the parser now replaces (lazily, i.e. smallest possible region) any areas enclosed by `<` and `>` such that `ImageN` is contained within (`N` being a number between `1` and `5`).
#352

Changed image parsing to regex to fix issue

---

client/react/frontpage/components/BlogPostPage.scss
client/react/frontpage/components/PromoBanner.js

The scrolling box on blog post page looked weird. The winter apps banner is outdated too. 
Small CSS changes.

removed blogpostpage scroll and updated banner

---

defaultPasswords.json

Update defaultPasswords.json
Replaced old passwords with updated ones. Added new passwords.
Copied and pasted current passwords.json to defaultPasswords.json
[#387](https://github.com/uclaradio/uclaradio.com/issues/387)
You should see a General Manager profile under DJ's page

updated defaultPasswords.json

---

client/react/frontpage/components/DiscoFeatures.scss

Fixed div clicking bug

---

README.md

Blogposts setup is outdated so I removed it. Blogposts should still be fetched from the API (gettingthe old posts shouldn't be necessary locally).

Deleted Blogposts setup from README

---

client/react/frontpage/components/FrontPageNavbar.js
client/react/frontpage/components/FrontPageNavbar.scss

Clea (Digipress Manager) asked for BETA to be removed to make us radio look more professional in order to get better access to press passes! We still have a lot of work to do, but the urgency makes sense. 
Deletion of BETA in CSS/HTML.

removed beta

---

app/database/db.js

Website now attempts to use a username and password drawn from `passwords.json` to connect to the MongoDB instance. This will still work with a database that doesn't have auth enabled, which means local development workflows can remain unchanged!
#424

Added MongoDB authorization

---

client/react/frontpage/frontpage.scss

Changed the frontpage font from Comic Sans MS back to apercuregular
Comic Sans did not look professional :(
**Operating System:**   
**Node Version:**

Revert Frontpage font

---

app/app.js

**NOTE:** Don't merge this until the questions raised in the issue linked below are addressed.
#433

Set up ping at regular interval

---

README.md
scripts/setup_ubuntu.sh

To make life easier for windows people 
The new Windows approach is to utilize Windows Subsystem for Linux.  Specifically through installing an ubuntu terminal, the set up will become very similar to the Mac (and Linux) set up.  This means that there won't be need for 2 Powershell scripts and excessive downloading of different libraries/add-on softwares to install those libraries.  However, there are minor differences to the Mac set up, main one being that Ubuntu does not need a software like Homebrew and can just use sudo apt-get to retrieve libraries.  And that the WSL has an error with getting yarn and yarn has to be retrieved with curl directly from its website.  
The README was also updated with the new steps to use the ubuntu script as well as a few errors that I encountered while …

Adding how to use WSL ubuntu to set up environment 

---

app/routes/index.js

This PR adds the ability for a user to specify a future date in the **Published at** field in Keystone in order to schedule a blog post to be added at that point in time. Note that no updates to `uclaradio-blog` are required; the post will still be added to Keystone's database, but the website will only pull posts whose `publishedAt` fields (if defined) are before the current date/time.
#435

Added blog post scheduling functionality

---

client/react/frontpage/Frontpage.js
client/react/frontpage/components/AboutPage.js
client/react/frontpage/components/AboutPage.scss
client/react/frontpage/components/PrivacyPolicyPage.js
client/react/frontpage/components/PrivacyPolicyPage.scss
package-lock.json
package.json

Updated the design of the about page based on a Figma design. About page now has a contact section, an about section, and a policy section that has a brief summary. 
**Operating System:**   
**Node Version:**

Policy Page styled

---

app/routes/index.js
client/react/frontpage/Frontpage.js
client/react/frontpage/components/BlogPostInfo.js
client/react/frontpage/components/BlogPostInfo.scss

Adds featured blog post (really the latest blog post) to the sidebar
https://github.com/uclaradio/uclaradio.com/issues/299

Added featured blog post to sidebar

---

app/routes/index.js
client/react/frontpage/Frontpage.js
client/react/frontpage/components/BlogPostInfo.js
client/react/frontpage/components/BlogPostInfo.scss

Reverts uclaradio/uclaradio.com#443
Probably my bad LOL. I forgot to restart the backend.

Revert "Revert "Katie/featured blog post""

---

app/routes/index.js
client/react/frontpage/Frontpage.js
client/react/frontpage/components/BlogPostInfo.js
client/react/frontpage/components/BlogPostInfo.scss

Trying featured blog post with existing route, to see if new route isn't registering for some reason. https://github.com/uclaradio/uclaradio.com/pull/447

Latest blog post with existing route

---

client/react/frontpage/components/BlogPage.scss

Fix image scaling issues that stretch and squash cover images for blog posts to fit the container.
Added `object-fit` and `object-position` fields to the `.postImage` class, which is the class used by an `<img>` tag in the blog post list item. Now, the images are centered and scaled to fill the container, but their aspect ratios are maintained, so they are cropped instead of squashed.
| Before | After |
| --- | --- |
| ![Screenshot_20190516_131340](https://user-images.githubusercontent.com/30734384/57883999-8aff2c00-77dc-11e9-8500-9103be18976e.png) | ![Screenshot_20190516_131353](https://user-images.githubusercontent.com/30734384/57884007-8e92b300-77dc-11e9-9d1b-381f83dfcf1b.png) |
#355

Fixed image stretching in blog post list page

---

client/react/frontpage/components/BlogPage.js
client/react/frontpage/components/BlogSearch.js

Appended author name(s) to searchValue
[414](https://github.com/uclaradio/uclaradio.com/issues/414)
**Operating System:**   
**Node Version:**

Search by Author Implemented

---

.github/CODEOWNERS

Like the title says.
* Arjun: @arjunr00 
* Ishaan: @IshaanPota

Changed code owners to Arjun and Ishaan
